### ISSUE TITLE
Too much padding on `span.comment`

### ISSUE THREAD

**Issue by hatboysam** [etcet/HNES#81] opened 2015-04-20 04:29 UTC
I'm noticing a lot of padding lately, I think HN might have changed their CSS and this extension is adding padding where it is not needed.

http://i.imgur.com/wHIQK37.png?1

**Comment by etcet** [comment] 2015-04-26 21:52
Dupe of issue #80 but thank you for the report and screenshot.

**Closed by etcet** 2015-04-26 21:52 UTC
Labels: duplicate
